language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

notifications:
  email: false

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test2;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test3;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE SCHEMA test2;' -U postgres -d cakephp_test; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE SCHEMA test3;' -U postgres -d cakephp_test; fi"

  - cd ..

  - git clone git://github.com/cakephp/cakephp.git cakephp-2.3
  - cd cakephp-2.3; git checkout 2.3.5
  - cd ..

  - cp -r cakephp-2.3 cakephp-2.4
  - cd cakephp-2.4; git checkout origin/2.4
  - cd ..

  - cp -r cakephp-sqs cakephp-2.3/app/Plugin/SQS
  - cp -r cakephp-sqs cakephp-2.4/app/Plugin/SQS

  - chmod -R 0777 ./cakephp-2.3/app/tmp
  - chmod -R 0777 ./cakephp-2.4/app/tmp

  - mkdir composer
  - cd composer
  - wget https://gist.github.com/Jippi/5716937/raw/composer.json
  - composer install
  - cd ..

  - curl https://gist.github.com/Jippi/5716937/raw/database.php -o cakephp-2.3/app/Config/database.php
  - cp cakephp-2.3/app/Config/database.php cakephp-2.4/app/Config/database.php

  - echo "require_once dirname('${TRAVIS_BUILD_DIR}') . '/composer/vendor/autoload.php';" >> cakephp-2.3/app/Config/bootstrap.php
  - echo "require_once dirname('${TRAVIS_BUILD_DIR}') . '/composer/vendor/autoload.php';" >> cakephp-2.4/app/Config/bootstrap.php

script:
  - cd cakephp-2.3 && ./lib/Cake/Console/cake test SQS AllSQS --stderr
  - cd ..
  - cd cakephp-2.4 && ./lib/Cake/Console/cake test SQS AllSQS --stderr
